### ISSUE TITLE
ListOfEdgesGraphReader: Handle duplicate edges and/or maintain specified/sorted order

### ISSUE THREAD

**Issue by pankajgupta** [twitter/cassovary#185]
com.twitter.cassovary.util.io.ListOfEdgesGraphReader reads each edge in input one by one and will form an adjacency list (neighbor nodes of a source node) in the same order as it sees it and does not handle duplicates. Add variables to this class constructor to:
1. Handle duplicate edges or not
2. Keep original order in input or keep neighbors of a node in sorted order

https://github.com/twitter/cassovary/pull/184 (later reverted) only handled duplicate edges but in doing so did not keep the original order of edges seen.

**Comment by tlasica** [comment]
I see two approaches possible:
a) using smart structure instead of ArrayBuffer[Int] to do dedup during adding neighbours
b) do post processing for sorting or duplicate elimination

I assume that the signature of below function should remain unchanged to makes things easier
```scala
def readEdgesBySource(): (Int2ObjectMap[ArrayBuffer[Int]], Int2IntArrayMap) = {
```

Solution (a) introduces additional memory overhead for keeping both set and list in case of unsorted with duplicates elimination plus some extra memory copying at the end of the processing. It should come in zero cost if neither deduplication nor sorting is applied. 

Solution (b) can do the postprocessing on each value in the edgesBySource map. It will cost additional memory per neighbours list (much less than solution (a)). Memory copying will happen also in this case for some cases e.g. dedup with original order.

Time complexity ibn both cases is similar of n * O(klogk) for sorting (when n is number of nodes and k is #of neighbours). Duplicate elimination in both cases is feasible in additional O(m) cost (m = #edges).

Do you have any suggestions which approach to follow?
I have (a) implemented and tested - as it seemed to be more elegant one :-)

**Comment by pankajgupta** [comment]
IIUC you are saying that (a) requires at least 2x memory in your implementation as you would keep both a set and a list? If so, that is just too much. You could keep only a SortedSet in (a) and then convert to Array at the end. Alternatively, post-processing as in (b) looks good too.

**Comment by tlasica** [comment]
Yes, in solution (a) there is twice as much memory used. Unfortunately it is impossible to use only  SortedSet(a) if you want to keep the order of neighbours as given in the file. It is possible if we decide that deduplication=true and sort=false is not acceptable.

**Comment by pankajgupta** [comment]
Makes sense -- (b) sounds more flexible then, doesn't it?
